apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: shipping
      project: roboshop
      tier: backend
      #pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: shipping
          image: tonyduck/shipping:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shipping
          ports:
            - name: liveness-port
              containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi" #Java is mmory hungry application

          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
            initialDelaySeconds: 60 
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            initialDelaySeconds: 60 
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    component: shipping
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port - clusterIPport
      targetPort: 8080
# ---
#HPA resource
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    #HPA always wathces the deployment
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5 # 70 is the real value