#create  default service, headless service, statefulset(PVC template)

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port - clusterIPport
      targetPort: 27017
---
#Headless service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port - clusterIPport
      targetPort: 27017      
---
# Statefulset- just like deploymewnt
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  serviceName: "mongodb-headless" #this should be headless service name 
  replicas: 2 # by default is 1
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: tonyduck/mongodb:v1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
          #PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi    
