apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

# ---
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    component: mysql
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #service port - clusterIPport
      targetPort: 3306
---
#Headless service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    component: mysql
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #service port - clusterIPport
      targetPort: 3306      
---
# Statefulset- just like deploymewnt
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: db
  serviceName: "mysql-headless" #this should be headless service name 
  replicas: 1 # by default is 1
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: db
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: tonyduck/mysql:v1
        volumeMounts:
          - name: mysql
            mountPath: /data/db
          - name: mysql-config
            mountPath: /etc/mysql/conf.d/my.cnf
            subPath: my.cnf
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
          #PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi    

